# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collision_map_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vector2d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='collision_map_request.proto',
  package='collision_map_creator_msgs.msgs',
  serialized_pb=_b('\n\x1b\x63ollision_map_request.proto\x12\x1f\x63ollision_map_creator_msgs.msgs\x1a\x0evector2d.proto\"\x8f\x02\n\x13\x43ollisionMapRequest\x12(\n\tupperLeft\x18\x01 \x02(\x0b\x32\x15.gazebo.msgs.Vector2d\x12)\n\nupperRight\x18\x02 \x02(\x0b\x32\x15.gazebo.msgs.Vector2d\x12)\n\nlowerRight\x18\x03 \x02(\x0b\x32\x15.gazebo.msgs.Vector2d\x12(\n\tlowerLeft\x18\x04 \x02(\x0b\x32\x15.gazebo.msgs.Vector2d\x12\x0e\n\x06height\x18\x05 \x02(\x01\x12\x12\n\nresolution\x18\x06 \x02(\x01\x12\x12\n\x08\x66ilename\x18\x07 \x01(\t:\x00\x12\x16\n\tthreshold\x18\x08 \x01(\x05:\x03\x32\x35\x35')
  ,
  dependencies=[vector2d_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COLLISIONMAPREQUEST = _descriptor.Descriptor(
  name='CollisionMapRequest',
  full_name='collision_map_creator_msgs.msgs.CollisionMapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upperLeft', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.upperLeft', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upperRight', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.upperRight', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowerRight', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.lowerRight', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lowerLeft', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.lowerLeft', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.height', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.resolution', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.filename', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='collision_map_creator_msgs.msgs.CollisionMapRequest.threshold', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=255,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=352,
)

_COLLISIONMAPREQUEST.fields_by_name['upperLeft'].message_type = vector2d_pb2._VECTOR2D
_COLLISIONMAPREQUEST.fields_by_name['upperRight'].message_type = vector2d_pb2._VECTOR2D
_COLLISIONMAPREQUEST.fields_by_name['lowerRight'].message_type = vector2d_pb2._VECTOR2D
_COLLISIONMAPREQUEST.fields_by_name['lowerLeft'].message_type = vector2d_pb2._VECTOR2D
DESCRIPTOR.message_types_by_name['CollisionMapRequest'] = _COLLISIONMAPREQUEST

CollisionMapRequest = _reflection.GeneratedProtocolMessageType('CollisionMapRequest', (_message.Message,), dict(
  DESCRIPTOR = _COLLISIONMAPREQUEST,
  __module__ = 'collision_map_request_pb2'
  # @@protoc_insertion_point(class_scope:collision_map_creator_msgs.msgs.CollisionMapRequest)
  ))
_sym_db.RegisterMessage(CollisionMapRequest)


# @@protoc_insertion_point(module_scope)
