# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Float.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Float.proto',
  package='std_msgs.msgs',
  serialized_pb=_b('\n\x0b\x46loat.proto\x12\rstd_msgs.msgs\"\x15\n\x05\x46loat\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FLOAT = _descriptor.Descriptor(
  name='Float',
  full_name='std_msgs.msgs.Float',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='std_msgs.msgs.Float.data', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['Float'] = _FLOAT

Float = _reflection.GeneratedProtocolMessageType('Float', (_message.Message,), dict(
  DESCRIPTOR = _FLOAT,
  __module__ = 'Float_pb2'
  # @@protoc_insertion_point(class_scope:std_msgs.msgs.Float)
  ))
_sym_db.RegisterMessage(Float)


# @@protoc_insertion_point(module_scope)
