# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Groundtruth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Groundtruth.proto',
  package='gps_msgs.msgs',
  serialized_pb=_b('\n\x11Groundtruth.proto\x12\rgps_msgs.msgs\"\xf6\x01\n\x0bGroundtruth\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12\x14\n\x0clatitude_rad\x18\x02 \x02(\x01\x12\x15\n\rlongitude_rad\x18\x03 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x02(\x01\x12\x15\n\rvelocity_east\x18\x05 \x01(\x01\x12\x16\n\x0evelocity_north\x18\x06 \x01(\x01\x12\x13\n\x0bvelocity_up\x18\x07 \x01(\x01\x12\x14\n\x0c\x61ttitude_q_w\x18\x08 \x01(\x01\x12\x14\n\x0c\x61ttitude_q_x\x18\t \x01(\x01\x12\x14\n\x0c\x61ttitude_q_y\x18\n \x01(\x01\x12\x14\n\x0c\x61ttitude_q_z\x18\x0b \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GROUNDTRUTH = _descriptor.Descriptor(
  name='Groundtruth',
  full_name='gps_msgs.msgs.Groundtruth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='gps_msgs.msgs.Groundtruth.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude_rad', full_name='gps_msgs.msgs.Groundtruth.latitude_rad', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude_rad', full_name='gps_msgs.msgs.Groundtruth.longitude_rad', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='gps_msgs.msgs.Groundtruth.altitude', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_east', full_name='gps_msgs.msgs.Groundtruth.velocity_east', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_north', full_name='gps_msgs.msgs.Groundtruth.velocity_north', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_up', full_name='gps_msgs.msgs.Groundtruth.velocity_up', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude_q_w', full_name='gps_msgs.msgs.Groundtruth.attitude_q_w', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude_q_x', full_name='gps_msgs.msgs.Groundtruth.attitude_q_x', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude_q_y', full_name='gps_msgs.msgs.Groundtruth.attitude_q_y', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attitude_q_z', full_name='gps_msgs.msgs.Groundtruth.attitude_q_z', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['Groundtruth'] = _GROUNDTRUTH

Groundtruth = _reflection.GeneratedProtocolMessageType('Groundtruth', (_message.Message,), dict(
  DESCRIPTOR = _GROUNDTRUTH,
  __module__ = 'Groundtruth_pb2'
  # @@protoc_insertion_point(class_scope:gps_msgs.msgs.Groundtruth)
  ))
_sym_db.RegisterMessage(Groundtruth)


# @@protoc_insertion_point(module_scope)
