# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MotorSpeed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MotorSpeed.proto',
  package='mav_msgs.msgs',
  serialized_pb=_b('\n\x10MotorSpeed.proto\x12\rmav_msgs.msgs\"%\n\nMotorSpeed\x12\x17\n\x0bmotor_speed\x18\x01 \x03(\x02\x42\x02\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOTORSPEED = _descriptor.Descriptor(
  name='MotorSpeed',
  full_name='mav_msgs.msgs.MotorSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_speed', full_name='mav_msgs.msgs.MotorSpeed.motor_speed', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['MotorSpeed'] = _MOTORSPEED

MotorSpeed = _reflection.GeneratedProtocolMessageType('MotorSpeed', (_message.Message,), dict(
  DESCRIPTOR = _MOTORSPEED,
  __module__ = 'MotorSpeed_pb2'
  # @@protoc_insertion_point(class_scope:mav_msgs.msgs.MotorSpeed)
  ))
_sym_db.RegisterMessage(MotorSpeed)


_MOTORSPEED.fields_by_name['motor_speed'].has_options = True
_MOTORSPEED.fields_by_name['motor_speed']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
