# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opticalFlow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='opticalFlow.proto',
  package='opticalFlow_msgs.msgs',
  serialized_pb=_b('\n\x11opticalFlow.proto\x12\x15opticalFlow_msgs.msgs\"\xa2\x02\n\x0bopticalFlow\x12\x11\n\ttime_usec\x18\x01 \x02(\x05\x12\x11\n\tsensor_id\x18\x02 \x02(\x05\x12\x1b\n\x13integration_time_us\x18\x03 \x02(\x05\x12\x14\n\x0cintegrated_x\x18\x04 \x02(\x02\x12\x14\n\x0cintegrated_y\x18\x05 \x02(\x02\x12\x18\n\x10integrated_xgyro\x18\x06 \x02(\x02\x12\x18\n\x10integrated_ygyro\x18\x07 \x02(\x02\x12\x18\n\x10integrated_zgyro\x18\x08 \x02(\x02\x12\x13\n\x0btemperature\x18\t \x02(\x02\x12\x0f\n\x07quality\x18\n \x02(\x05\x12\x1e\n\x16time_delta_distance_us\x18\x0b \x02(\x05\x12\x10\n\x08\x64istance\x18\x0c \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OPTICALFLOW = _descriptor.Descriptor(
  name='opticalFlow',
  full_name='opticalFlow_msgs.msgs.opticalFlow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_usec', full_name='opticalFlow_msgs.msgs.opticalFlow.time_usec', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='opticalFlow_msgs.msgs.opticalFlow.sensor_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integration_time_us', full_name='opticalFlow_msgs.msgs.opticalFlow.integration_time_us', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrated_x', full_name='opticalFlow_msgs.msgs.opticalFlow.integrated_x', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrated_y', full_name='opticalFlow_msgs.msgs.opticalFlow.integrated_y', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrated_xgyro', full_name='opticalFlow_msgs.msgs.opticalFlow.integrated_xgyro', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrated_ygyro', full_name='opticalFlow_msgs.msgs.opticalFlow.integrated_ygyro', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integrated_zgyro', full_name='opticalFlow_msgs.msgs.opticalFlow.integrated_zgyro', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='opticalFlow_msgs.msgs.opticalFlow.temperature', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='opticalFlow_msgs.msgs.opticalFlow.quality', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_delta_distance_us', full_name='opticalFlow_msgs.msgs.opticalFlow.time_delta_distance_us', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='opticalFlow_msgs.msgs.opticalFlow.distance', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=335,
)

DESCRIPTOR.message_types_by_name['opticalFlow'] = _OPTICALFLOW

opticalFlow = _reflection.GeneratedProtocolMessageType('opticalFlow', (_message.Message,), dict(
  DESCRIPTOR = _OPTICALFLOW,
  __module__ = 'opticalFlow_pb2'
  # @@protoc_insertion_point(class_scope:opticalFlow_msgs.msgs.opticalFlow)
  ))
_sym_db.RegisterMessage(opticalFlow)


# @@protoc_insertion_point(module_scope)
