# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorImu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quaternion_pb2
import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorImu.proto',
  package='sensor_msgs.msgs',
  serialized_pb=_b('\n\x0fSensorImu.proto\x12\x10sensor_msgs.msgs\x1a\x10quaternion.proto\x1a\x0evector3d.proto\"\x91\x02\n\x03Imu\x12,\n\x0borientation\x18\x01 \x02(\x0b\x32\x17.gazebo.msgs.Quaternion\x12\"\n\x16orientation_covariance\x18\x02 \x03(\x02\x42\x02\x10\x01\x12/\n\x10\x61ngular_velocity\x18\x03 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\'\n\x1b\x61ngular_velocity_covariance\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x32\n\x13linear_acceleration\x18\x05 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12*\n\x1elinear_acceleration_covariance\x18\x06 \x03(\x02\x42\x02\x10\x01')
  ,
  dependencies=[quaternion_pb2.DESCRIPTOR,vector3d_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMU = _descriptor.Descriptor(
  name='Imu',
  full_name='sensor_msgs.msgs.Imu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orientation', full_name='sensor_msgs.msgs.Imu.orientation', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation_covariance', full_name='sensor_msgs.msgs.Imu.orientation_covariance', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='sensor_msgs.msgs.Imu.angular_velocity', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity_covariance', full_name='sensor_msgs.msgs.Imu.angular_velocity_covariance', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='sensor_msgs.msgs.Imu.linear_acceleration', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration_covariance', full_name='sensor_msgs.msgs.Imu.linear_acceleration_covariance', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=345,
)

_IMU.fields_by_name['orientation'].message_type = quaternion_pb2._QUATERNION
_IMU.fields_by_name['angular_velocity'].message_type = vector3d_pb2._VECTOR3D
_IMU.fields_by_name['linear_acceleration'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Imu'] = _IMU

Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), dict(
  DESCRIPTOR = _IMU,
  __module__ = 'SensorImu_pb2'
  # @@protoc_insertion_point(class_scope:sensor_msgs.msgs.Imu)
  ))
_sym_db.RegisterMessage(Imu)


_IMU.fields_by_name['orientation_covariance'].has_options = True
_IMU.fields_by_name['orientation_covariance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_IMU.fields_by_name['angular_velocity_covariance'].has_options = True
_IMU.fields_by_name['angular_velocity_covariance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_IMU.fields_by_name['linear_acceleration_covariance'].has_options = True
_IMU.fields_by_name['linear_acceleration_covariance']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
