# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SITLGps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SITLGps.proto',
  package='gps_msgs.msgs',
  serialized_pb=_b('\n\rSITLGps.proto\x12\rgps_msgs.msgs\"\xc6\x01\n\x07SITLGps\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12\x14\n\x0clatitude_deg\x18\x02 \x02(\x01\x12\x15\n\rlongitude_deg\x18\x03 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x02(\x01\x12\x0b\n\x03\x65ph\x18\x05 \x01(\x01\x12\x0b\n\x03\x65pv\x18\x06 \x01(\x01\x12\x10\n\x08velocity\x18\x07 \x01(\x01\x12\x15\n\rvelocity_east\x18\x08 \x01(\x01\x12\x16\n\x0evelocity_north\x18\t \x01(\x01\x12\x13\n\x0bvelocity_up\x18\n \x01(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SITLGPS = _descriptor.Descriptor(
  name='SITLGps',
  full_name='gps_msgs.msgs.SITLGps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='gps_msgs.msgs.SITLGps.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude_deg', full_name='gps_msgs.msgs.SITLGps.latitude_deg', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude_deg', full_name='gps_msgs.msgs.SITLGps.longitude_deg', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='gps_msgs.msgs.SITLGps.altitude', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eph', full_name='gps_msgs.msgs.SITLGps.eph', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='epv', full_name='gps_msgs.msgs.SITLGps.epv', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='gps_msgs.msgs.SITLGps.velocity', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_east', full_name='gps_msgs.msgs.SITLGps.velocity_east', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_north', full_name='gps_msgs.msgs.SITLGps.velocity_north', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_up', full_name='gps_msgs.msgs.SITLGps.velocity_up', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['SITLGps'] = _SITLGPS

SITLGps = _reflection.GeneratedProtocolMessageType('SITLGps', (_message.Message,), dict(
  DESCRIPTOR = _SITLGPS,
  __module__ = 'SITLGps_pb2'
  # @@protoc_insertion_point(class_scope:gps_msgs.msgs.SITLGps)
  ))
_sym_db.RegisterMessage(SITLGps)


# @@protoc_insertion_point(module_scope)
