# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Wind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import time_pb2
import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Wind.proto',
  package='wind_msgs.msgs',
  serialized_pb=_b('\n\nWind.proto\x12\x0ewind_msgs.msgs\x1a\ntime.proto\x1a\x0evector3d.proto\"`\n\x04Wind\x12\x10\n\x08\x66rame_id\x18\x01 \x02(\t\x12 \n\x05stamp\x18\x02 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12$\n\x05\x66orce\x18\x03 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d')
  ,
  dependencies=[time_pb2.DESCRIPTOR,vector3d_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WIND = _descriptor.Descriptor(
  name='Wind',
  full_name='wind_msgs.msgs.Wind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='wind_msgs.msgs.Wind.frame_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='wind_msgs.msgs.Wind.stamp', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='force', full_name='wind_msgs.msgs.Wind.force', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=154,
)

_WIND.fields_by_name['stamp'].message_type = time_pb2._TIME
_WIND.fields_by_name['force'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Wind'] = _WIND

Wind = _reflection.GeneratedProtocolMessageType('Wind', (_message.Message,), dict(
  DESCRIPTOR = _WIND,
  __module__ = 'Wind_pb2'
  # @@protoc_insertion_point(class_scope:wind_msgs.msgs.Wind)
  ))
_sym_db.RegisterMessage(Wind)


# @@protoc_insertion_point(module_scope)
